/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author darkd
 */
public class StartBackground extends javax.swing.JPanel
{

    ImageIcon image;
    ImageIcon image2;
    private int index;

    /**
     * Creates new form StartBackground
     */
    public StartBackground()
    {
        initComponents();
        this.image = new ImageIcon(getClass().getResource("../Images/begin.jpg"));
        this.image2 = new ImageIcon(getClass().getResource("../Images/minar.jpg"));
        this.index = 2;
    }

    @Override
    protected void paintComponent(Graphics grphcs)
    {

        super.paintComponent(grphcs); //To change body of generated methods, choose Tools | Templates.
        if (this.image != null && this.index == 1)
            grphcs.drawImage(this.image.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);
        else if (this.image != null && this.index == 2)
            grphcs.drawImage(this.image2.getImage(), 0, 0, this.getWidth(), this.getHeight(), null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @return the index
     */
    public int getIndex()
    {
        return index;
    }

    /**
     * @param index the index to set
     */
    public void setIndex(int index)
    {
        this.index = index;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
