/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author darkd
 */
public class TypeMetal extends javax.swing.JDialog
{

    private String metal;

    /**
     * Creates new form TypeMetal
     *
     * @param parent
     * @param modal
     */
    public TypeMetal(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        this.metal = "";
        initComponents();
        this.setTitle("Metal");
        this.setLocationRelativeTo(null);
        this.setVisible(true);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        buttonOro = new javax.swing.JButton();
        buttonPlata = new javax.swing.JButton();
        buttonCobre = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        buttonOro.setBackground(new java.awt.Color(204, 204, 204));
        buttonOro.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buttonOro.setForeground(new java.awt.Color(0, 0, 0));
        buttonOro.setText("ORO");
        buttonOro.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonOroActionPerformed(evt);
            }
        });

        buttonPlata.setBackground(new java.awt.Color(204, 204, 204));
        buttonPlata.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buttonPlata.setForeground(new java.awt.Color(0, 0, 0));
        buttonPlata.setText("PLATA");
        buttonPlata.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonPlataActionPerformed(evt);
            }
        });

        buttonCobre.setBackground(new java.awt.Color(204, 204, 204));
        buttonCobre.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        buttonCobre.setForeground(new java.awt.Color(0, 0, 0));
        buttonCobre.setText("COBRE");
        buttonCobre.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                buttonCobreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonCobre)
                    .addComponent(buttonPlata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonOro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(buttonOro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonPlata)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonCobre)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonPlataActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonPlataActionPerformed
    {//GEN-HEADEREND:event_buttonPlataActionPerformed
        this.metal = "plata";
        this.setVisible(false);
    }//GEN-LAST:event_buttonPlataActionPerformed

    private void buttonOroActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonOroActionPerformed
    {//GEN-HEADEREND:event_buttonOroActionPerformed
        this.metal = "oro";
        this.setVisible(false);
    }//GEN-LAST:event_buttonOroActionPerformed

    private void buttonCobreActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_buttonCobreActionPerformed
    {//GEN-HEADEREND:event_buttonCobreActionPerformed
        this.metal = "cobre";
        this.setVisible(false);
    }//GEN-LAST:event_buttonCobreActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[])
//    {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try
//        {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
//            {
//                if ("Nimbus".equals(info.getName()))
//                {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        }
//        catch (ClassNotFoundException ex)
//        {
//            java.util.logging.Logger.getLogger(TypeMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (InstantiationException ex)
//        {
//            java.util.logging.Logger.getLogger(TypeMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (IllegalAccessException ex)
//        {
//            java.util.logging.Logger.getLogger(TypeMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        catch (javax.swing.UnsupportedLookAndFeelException ex)
//        {
//            java.util.logging.Logger.getLogger(TypeMetal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable()
//        {
//            public void run()
//            {
//                TypeMetal dialog = new TypeMetal(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter()
//                {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e)
//                    {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonCobre;
    private javax.swing.JButton buttonOro;
    private javax.swing.JButton buttonPlata;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the metal
     */
    public String getMetal()
    {
        return metal;
    }

    /**
     * @param metal the metal to set
     */
    public void setMetal(String metal)
    {
        this.metal = metal;
    }
}
